version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_t1_academy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t1_academy_db
    ports:
      - "5430:5432"
