version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_t1_academy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t1_academy_db
    ports:
      - "5430:5432"

  t1_kafka:
    image: 'bitnami/kafka:3.1.2'
    container_name: t1_kafka
    ports:
      - '9032:9032'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,INSIDE://:9031,OUTSIDE://:9032
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://:9031,OUTSIDE://localhost:9032
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    container_name: kafka-ui
    ports:
      - '8012:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=t1_kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=t1_kafka:9031
    depends_on:
      - t1_kafka